name: usyre
description: A simple user management platform.
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  crypto: ^3.0.2
  mongo_dart: ^0.8.2
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  uuid: ^3.0.7
